# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1361127049);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1361127169);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 215040);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 8);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20130206201250");
user_pref("browser.startup.homepage_override.mstone", "18.0.2");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.warnOnQuit", false);
user_pref("devtools.errorconsole.enabled", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"1e8e607c-e1f8-403c-80ba-41eb5bce2a88@jetpack\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"/home/alex/Computech/projects/trelloscrum-firefox/dev/extensions/1e8e607c-e1f8-403c-80ba-41eb5bce2a88@jetpack.xpi\"}}");
user_pref("extensions.checkCompatibility.18.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0.2");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1360182865000}}},{\"name\":\"app-profile\",\"addons\":{\"1e8e607c-e1f8-403c-80ba-41eb5bce2a88@jetpack\":{\"descriptor\":\"/home/alex/Computech/projects/trelloscrum-firefox/dev/extensions/1e8e607c-e1f8-403c-80ba-41eb5bce2a88@jetpack.xpi\",\"mtime\":1361127047000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "18.0.2");
user_pref("extensions.lastPlatformVersion", "18.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.testpilot.runStudies", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("gecko.buildID", "20130206201250");
user_pref("gecko.mstone", "18.0.2");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("javascript.options.strict", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 10913);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1361127047);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1363719052);
user_pref("urlclassifier.updateinterval", 172800);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
